RAF2019/urls.py
from django.contrib import admin
from django.urls import path, include
from korisnici import views

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('reset_lozinka/', auth_views.PasswordResetView.as_view(template_name='korisnici/reset.html'), name = 'password_reset'),
    path('reset_lozinka/kraj/', auth_views.PasswordResetView.as_view(template_name='korisnici/reset_potvrda.html'), name = 'password_reset_done'),
    path('reset_lozinka/potvrda/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='korisnici/resetuj.html'), name = 'password_reset_confirm'),
    path('reset_lozinka/zavrsio/', auth_views.PasswordResetCompleteView.as_view(template_name='korisnici/kraj.html'), name = 'password_reset_complete'),
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('korisnici/', include('korisnici.urls'), name="korisnici"),
    path('dogadjaji/', include('dogadjaji.urls'), name="dogadjaji"),
    path('logout/', views.logoutPage, name="logoutPage"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogadjaji/urls.py
from django.urls import path, include
from dogadjaji import views

app_name = 'dogadjaji'

urlpatterns = [
    path('novi_dogadjaj/', views.dodajDogadjaj, name='nov'),
    path('pretraga/', views.pretraga, name='pretraga'),
    path('prijava/<int:id_dog>', views.prijava, name='prijava'),
    path('moji_dogadjaji/', views.mojiDogadjaji, name='moji_dogadjaji'),
    path('prijava_rezultat/<int:prijava_id>', views.prijava_rezultat, name='prijava_rezultat'),
    path('kraj/<int:dogadjaj_kraj_id>/', views.kraj, name='kraj'),
    path('otkaz/<int:dogadjaj_za_otkaz>/', views.otkaz, name='otkaz'),
    path('ocenjivanje/<int:id_dog>/', views.ocenjuj, name='ocenjivanje'),
    path('ocena/<int:id_dog>/<int:usid>/', views.ocena, name='ocena'),
    path('<int:id_dog>/', views.pregled, name='pregled_dogadjaja'),
    path('izbaci/<int:id_dog>/<int:usid>/', views.izbaci, name='izbacivanje'),
    path('pozovi/<int:id_dog>/', views.pozovi, name='pozovi'),
    path('pozivi/', views.pozivi, name='pozivi'),

]

korisnici/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "korisnici"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profil/', views.clanInfo, name='clanInfo'),
    path('login/', views.loginPage, name='loginPage'),
    path('podesavanja/', views.podesavanja, name='podesavanja'),
    path('lozinka/', views.promenaLozinke, name='lozinka'),
    path('pregled/<int:usid>', views.pregled, name='pregled'),

    ]

dogadjaji/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator
from korisnici.models import Clanovi


# Create your models here.


class Dogadjaji(models.Model):
    TIME_ZONE = 'Europe/Belgrade'
    sportovi = (("Fudbal", "Fudbal"), ("Kosarka", "Kosarka"), ("Tenis", "Tenis"),
                ("Odbojka", "Odbojka"), ("Rukomet", "Rukomet"), ("Stoni tenis", "Stoni tenis"), ("Bilijar", "Bilijar"))
    novac = (("Nema nagrada", "Nema nagrada"), ("Ima nagrada", "Ima nagrada"))
    gradovi = (('Beograd', 'Beograd'), ('Valjevo', 'Valjevo'), ('Vranje', 'Vranje'), ('Zaječar', 'Zaječar'),
               ('Zrenjanin', 'Zrenjanin'), ('Jagodina', 'Jagodina'), ('Kragujevac', 'Kragujevac'),
               ('Kraljevo', 'Kraljevo'), ('Kruševac', 'Kruševac'), ('Leskovac', 'Leskovac'), ('Loznica', 'Loznica'),
               ('Niš', 'Niš'), ('Novi Pazar', 'Novi Pazar'), ('Novi Sad', 'Novi Sad'), ('Pančevo', 'Pančevo'),
               ('Požarevac', 'Požarevac'), ('Priština', 'Priština'), ('Smederevo', 'Smederevo'), ('Sombor', 'Sombor'),
               ('Sremska Mitrovica', 'Sremska Mitrovica'), ('Subotica', 'Subotica'), ('Užice', 'Užice'),
               ('Čačak', 'Čačak'), ('Šabac', 'Šabac'), ('Pirot', 'Pirot'))

    organizator = models.ForeignKey(Clanovi, on_delete=models.CASCADE, unique=False)
    datum_kreiranja = models.DateField(default=timezone.now)

    naziv = models.CharField(max_length=150, blank=False, null=False)
    datum_odrzavanja = models.DateField()
    opis = models.TextField(max_length=1000, blank=False, null=False)
    potrebno_igraca = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    novcana_nagrada = models.CharField(max_length=100, choices=novac, default="Nema novcane nagrade")
    novac_za_prijavu = models.PositiveIntegerField()
    grad = models.CharField(max_length=254, default="Nije naveden grad", choices=gradovi)
    mesto = models.CharField(max_length=150, blank=False)
    odrzano = models.BooleanField(default=False)
    sport = models.CharField(max_length=254, choices=sportovi, blank=False, null=False, default='Fudbal')
    ima_igraca = models.PositiveIntegerField(null=False, default=0)


class Prijava(models.Model):
    TIME_ZONE = 'Europe/Belgrade'

    status_prijave = (("Primljen", "Primljen"), ("Odbijen", "Odbijen"), ('Ceka se odgovor', 'Ceka se odgovor'))

    prijava_za_dogadjaj = models.ForeignKey(Dogadjaji, on_delete=models.CASCADE, unique=False)
    prijavu_poslao = models.ForeignKey(Clanovi, on_delete=models.CASCADE, unique=False)

    organizator = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)

    datum_prijave = models.DateField(default=timezone.now)

    primljen = models.CharField(max_length=100, default="Ceka se odgovor", choices=status_prijave)


class Ocenjivanje(models.Model):
    ocenio = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)

    koga_ocenio = models.ForeignKey(Clanovi, on_delete=models.CASCADE, unique=False)

    koji_dogadjaj = models.ForeignKey(Dogadjaji, on_delete=models.CASCADE, unique=False)

    ocena = models.FloatField(default=0)
    komentar = models.CharField(max_length=1000, blank=True, null=False, default="")
    datum_ocenjivanja = models.DateField(default=timezone.now)


class Glasao(models.Model):
    igrac = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)
    koji_dogadjaj = models.ForeignKey(Dogadjaji, on_delete=models.CASCADE, unique=False)
    zavrsio = models.BooleanField(default=False)


class Poziv(models.Model):
    status_prijave = (("Nije pogledano", "Nije pogledano"), ("Jeste pogledano", "Jeste pogledano"))
    pozvao = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)
    ko_je_pozvan = models.ForeignKey(Clanovi, on_delete=models.CASCADE, unique=False)
    koji_dogadjaj = models.ForeignKey(Dogadjaji, on_delete=models.CASCADE, unique=False)
    pogledano = models.CharField(max_length=100, default="Nije pogledano", choices=status_prijave)
    datum = models.DateField(default=timezone.now)

dogadjaji/views.py
from django.shortcuts import render

from .forms import df, Pretraga
from .models import Dogadjaji, Prijava, Ocenjivanje, Glasao, Poziv
from korisnici.models import Clanovi
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone


# Create your views here.
@login_required
def dodajDogadjaj(request):
    organizator = request.user
    clan = Clanovi.objects.get(user=organizator)
    ima = False
    if Dogadjaji.objects.filter(organizator=clan):
        ima = True
    if request.method == "POST":

        forma = df(data=request.POST)

        if forma.is_valid():
            naziv = forma.cleaned_data['naziv']
            mesto = forma.cleaned_data['mesto']
            opis = forma.cleaned_data['opis']
            datum_odrzavanja = forma.cleaned_data['datum_odrzavanja']
            novac_za_prijavu = forma.cleaned_data['novac_za_prijavu']
            potrebno_igraca = forma.cleaned_data['potrebno_igraca']
            grad = forma.cleaned_data['grad']
            sport = forma.cleaned_data['sport']
            novcana_nagrada = forma.cleaned_data['novcana_nagrada']
            dogadjaj = Dogadjaji(naziv=naziv, mesto=mesto, opis=opis, datum_odrzavanja=datum_odrzavanja,
                                 novac_za_prijavu=novac_za_prijavu, potrebno_igraca=potrebno_igraca,
                                 grad=grad, sport=sport, novcana_nagrada=novcana_nagrada, organizator=clan)
            dogadjaj.save()
            prijava_organizatora = Prijava(prijava_za_dogadjaj=dogadjaj, prijavu_poslao=clan, organizator=organizator,
                                           primljen="Primljen")
            prijava_organizatora.save()
            print('\n\n\nRADII\n\n\n')
        else:
            print("\n\n\nGRESKA")
            print(forma.errors)
            print("\n\n\n")

        return HttpResponseRedirect(reverse('korisnici:clanInfo'))

    else:
        forma = df
        return render(request, 'dogadjaji/nov_dogadjaj.html', context={"cl_form": forma})


@login_required
def pretraga(request):
    clan = Clanovi.objects.get(user=request.user)
    svi_dogadjaji = Dogadjaji.objects.all().exclude(organizator=clan).exclude(
        datum_odrzavanja__lt=timezone.now()).exclude()
    moje_prijave = Prijava.objects.filter(prijavu_poslao=clan)
    prijavio = []
    for jedna in moje_prijave:
        prijavio.append(jedna.prijava_za_dogadjaj_id)
    ima = False
    if Dogadjaji.objects.filter(organizator=clan):
        ima = True
    if request.method == 'POST':
        forma = Pretraga(request.POST)
        try:
            prosecna_ocena_pretrage = float(request.POST['rating'][:-1])
        except Exception as e:
            prosecna_ocena_pretrage = 0
            print(e)
        print("\n\n\n")
        print(prosecna_ocena_pretrage)
        print(type(prosecna_ocena_pretrage))
        print("\n\n\n")
        if forma.is_valid():
            grad = forma.cleaned_data['grad']
            sport = forma.cleaned_data['sport']
            ucesce = forma.cleaned_data['ucesce']
            nagrade = forma.cleaned_data['nagrade']
            potrebno_igraca = forma.cleaned_data['potrebno_igraca']
            trazi = True
            if ucesce == "Ne placa se ucesce":
                print('||||' + nagrade + "|||||||")
                if potrebno_igraca == 0:
                    print('igraca 0')
                    prikazani = svi_dogadjaji.filter(grad=grad, sport=sport, novac_za_prijavu=0,
                                                     novcana_nagrada=nagrade, odrzano=0,
                                                     organizator__prosecna_ocena__gte=prosecna_ocena_pretrage).exclude()

                else:
                    print('igraca 1')
                    prikazani = svi_dogadjaji.filter(grad=grad, sport=sport, potrebno_igraca=potrebno_igraca,
                                                     novcana_nagrada=nagrade, odrzano=0,
                                                     organizator__prosecna_ocena__gte=prosecna_ocena_pretrage)

            else:
                if potrebno_igraca == 0:
                    print("ima ucesca igraca 0")
                    prikazani = svi_dogadjaji.filter(grad=grad, sport=sport, novac_za_prijavu__gt=0,
                                                     novcana_nagrada=nagrade, odrzano=0,
                                                     organizator__prosecna_ocena__gte=prosecna_ocena_pretrage)
                else:
                    print('ima ucesca igraca 1')
                    prikazani = svi_dogadjaji.filter(grad=grad, sport=sport, novac_za_prijavu__gt=0,
                                                     novcana_nagrada=nagrade, odrzano=0,
                                                     potrebno_igraca=potrebno_igraca,
                                                     organizator__prosecna_ocena__gte=prosecna_ocena_pretrage)
        else:
            print(forma.errors)
            return HttpResponseRedirect(reverse('dogadjaji:pretraga'))
    else:
        trazi = False
        prikazani = svi_dogadjaji.filter(sport=clan.omiljeni_sport, grad=clan.grad,
                                         odrzano=0)
    forma = Pretraga
    print(prikazani)
    return render(request, 'dogadjaji/pretraga.html',
                  context={'trazi': trazi, 'prikazani': prikazani, 'forma': forma, "imaaa": ima, 'prijavio': prijavio})


@login_required
def prijava(request, id_dog):
    user = request.user
    clan = Clanovi.objects.get(user=user)

    dogadjaj = Dogadjaji.objects.get(id=id_dog)
    organizator = dogadjaj.organizator.user
    print(dogadjaj)
    print(clan.user.username)
    prijave_ovog_igraca = Prijava.objects.filter(prijavu_poslao=clan, prijava_za_dogadjaj=dogadjaj)
    if dogadjaj.ima_igraca >= dogadjaj.potrebno_igraca:
        return HttpResponse(
            "<head><title>MAXO</title></head>"
            "<br><br><br><br><h1 style='font-family:Arial;'><center>Maksimalan broj clanova je vec "
            "prijavljen na ovaj dogadjaj "
            "<br><br><small>Prozor ce se zatvoriti za 5 sekundi</small><center></h1>"
            "<script>setTimeout(function(){window.close();},5000);</script>")
    if prijave_ovog_igraca:
        return HttpResponse(
            "<head><title>MAXO</title></head>"
            "<br><br><br><br><h1 style='font-family:Arial;'><center>Vec ste se prijavili za ovaj "
            "dogadjaj<br><br><small>Prozor ce se zatvoriti za 5 sekundi</small><center></h1>"
            "<script>setTimeout(function(){window.close();},5000);</script>")
    if clan != dogadjaj.organizator:
        prijava = Prijava(prijavu_poslao=clan, prijava_za_dogadjaj=dogadjaj, organizator=organizator)
        prijava.save()
        return HttpResponse(
            "<head><title>MAXO</title></head>"
            "<br><br><br><br><h1 style='font-family:Arial;'><center>Prijava uspesno poslata."
            " Mozete zatvoriti ovu stranicu.<br><br><small>Prozor ce se zatvoriti za 5 sekundi</small></center></h1>"
            "<script>setTimeout(function(){window.close();},5000);</script>")
    else:
        return HttpResponse(
            "<head><title>MAXO</title></head>"
            "<br><br><br><br><h1 style='font-family:Arial;'><center>Ne mozete da se prijavite na svoj turnir."
            "<br><br><small>Prozor ce se zatvoriti za 5 sekundi</small></center></h1>"
            "<script>setTimeout(function(){window.close();},5000);</script>")


@login_required
def mojiDogadjaji(request):
    user = request.user
    clan = Clanovi.objects.get(user=user)
    moji_dogadjaji = Dogadjaji.objects.filter(organizator=clan, odrzano=0)
    moje_prijave_cekanje = Prijava.objects.filter(organizator=user, primljen="Ceka se odgovor")
    print(moje_prijave_cekanje)
    return render(request, 'dogadjaji/moji_dogadjaji.html',
                  context={'user': user, 'clan': clan, 'moji_dogadjaji': moji_dogadjaji, 'ceka': moje_prijave_cekanje})


@login_required
def prijava_rezultat(request, prijava_id):
    user = request.user
    if request.method == "POST":
        prijava_poslata = Prijava.objects.get(id=prijava_id)
        za_dogadjaj = Dogadjaji.objects.get(id=prijava_poslata.prijava_za_dogadjaj.id)
        print(za_dogadjaj)
        prijavu_poslao_clan = prijava_poslata.prijavu_poslao
        prijava_poslata_user = prijavu_poslao_clan.user
        if za_dogadjaj.potrebno_igraca == za_dogadjaj.ima_igraca:
            return HttpResponse("Dogadjaj je vec popunjen")
        if prijava_poslata.prijavu_poslao == user:
            return HttpResponse("Ne mozete se prijaviti na svoj turnir")
        else:
            if prijava_poslata.prijava_za_dogadjaj.odrzano == 1:
                return HttpResponse("Ovaj dogadjaj je vec zavrsen")
            else:
                if prijava_poslata.primljen == "Primljen":
                    return HttpResponse("Igrac je vec primljen na dogadjaj")
                elif prijava_poslata.primljen == "Odbijen":
                    return HttpResponse("Igrac je vec odbijen sa turnira")
                else:
                    if request.POST['izbor'] == "prihvati":

                        prijava_poslata.primljen = "Primljen"
                        prijava_poslata.save()
                        za_dogadjaj.ima_igraca += 1
                        za_dogadjaj.save()
                        print("\n\n\nPrimljen\n\n\n")
                        return HttpResponseRedirect(reverse("dogadjaji:moji_dogadjaji"))
                    else:
                        prijava_poslata.primljen = "Odbijen"
                        prijava_poslata.save()
                        print("\n\n\nPrimljen\n\n\n")
                        return HttpResponseRedirect(reverse("dogadjaji:moji_dogadjaji"))


    else:
        return HttpResponseRedirect(reverse("dogadjaji:moji_dogadjaji"))

dogadjaji/templates/dogadjaji/email.html
<body>
<a href="{% url 'dogadjaji:ocenjivanje' id_dog=dogadjaj.id %}">Link za ocenjivanje</a>
</body>

dogadjaji/templates/dogadjaji/nov_dogadjaj.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Organizovanje dogadjaja</title>
    <meta name="author" content="MAXO"/>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
      integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


    <link rel="shortcut icon" href="favicon.ico">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
</head>
<body onload="Gasi()">

<div class="container">

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">


        <div id="licni">
        <form method="post" class="fh5co-form animate-box" data-animate-effect="fadeIn">
            {% csrf_token %}
            <h2>Organizovanje dogadjaja <small><a href="{% url 'korisnici:clanInfo' %}">Vrati se na profil</a></small></h2>

            <div class="form-group">
                <p>Naziv dogadjaja</p>
                {{ cl_form.naziv }}
            </div>
            <div class="form-group">
                <p>Sport</p>
                {{ cl_form.sport }}
            </div>


            <div class="form-group">
                <p>Grad odrzavanja dogadjaja</p>
                {{ cl_form.grad }}
            </div>

            <div class="form-group">
                <p>Mesto na kojem se dogadjaj odrzava</p>
                {{ cl_form.mesto }}
            </div>

            <div class="form-group">
                <p>Koliko novca je potrebno za ucesce</p>
                {{ cl_form.novac_za_prijavu }}
            </div>



            <div class="form-group">
                <p>Hoce li biti nagrada</p>
                {{ cl_form.novcana_nagrada }}
            </div>


            <div class="form-group">
                <p>Opis</p>
                {{ cl_form.opis }}
            </div>


            <div class="form-group">
                <p>Kada ce dogadjaj biti odrzan</p>
                {{ cl_form.datum_odrzavanja }}
            </div>

            <div class="form-group">
                <p>Broj potrebnih igraca</p>
                {{ cl_form.potrebno_igraca }}
            </div>



            <div class="form-group">
                <input type="submit" value="Organizuj dogadjaj" class="btn btn-primary">
            </div>
        </form>
        </div>









    </div>
</div>
    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Placeholder -->
    <script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
    <!-- Waypoints -->
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <!-- Main JS -->
    <script src="{% static 'js/main.js' %}"></script>

<!-- NAMESTANJE PODATAKA -->
<script>
            $("#id_novac_za_prijavu").addClass('form-control');
            $("#id_novac_za_prijavu").attr('step','100');
            $("#id_novac_za_prijavu").attr('value','0');
            $("#id_novac_za_prijavu").addClass('form-control');
            $("#id_potrebno_igraca").addClass('form-control');
            $("#id_potrebno_igraca").attr('value','1');
            $("#id_potrebno_igraca").attr('min','1');

    </script>
<script>
    var danas = new Date().toISOString().split('T')[0];
document.getElementsByName("datum_odrzavanja")[0].setAttribute('min', danas);

</script>

</body>
</html>

dogadjaji/templates/dogadjaji/pozivi.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MAXO - pozivi</title>
    <meta name="author" content="MAXO"/>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="favicon.ico">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <!-- Modernizr JS -->
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>

</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">


            <h2 style="margin-bottom: -10%;">
                <a href="{% url 'korisnici:podesavanja' %}" style="text-decoration:none;"
                   class="fas fa-cogs w3-margin-right w3-text-teal" title="Podesavanja naloga"></a>

                <a href="{% url 'dogadjaji:pretraga' %}" style="text-decoration:none;"
                   class="fas fa-search w3-margin-right w3-text-teal" title="Pretrazuj"></a>
                <a href="{% url 'dogadjaji:nov' %}" style="text-decoration:none;"
                   class="fas fa-plus w3-margin-right w3-text-teal" title="Organizuj dogadjaj"></a>

                <a href="{% url 'korisnici:clanInfo' %}" style="text-decoration:none;"
                   class="fas fa-user w3-margin-right w3-text-teal" title="Vrati se na profil"></a>

                <a href="{% url 'logoutPage' %}" style="text-decoration:none; float: right;"
                   class="fas fa-sign-out-alt w3-margin-right w3-text-teal" title="Odjavi se"></a>


            </h2>

            <div class="fh5co-form animate-box" data-animate-effect="fadeIn">

                <p>Pozivi za vas</p>

                {% if pozivi %}
                    {% for poziv in pozivi %}
                    <h4>Korisnik <a href="{% url 'korisnici:pregled' usid=poziv.pozvao.id%}" target="_blank">{{ poziv.pozvao.username }}</a> vas poziva da pogledate dogadjaj:</h4>
                        <h4><a href="{% url 'dogadjaji:pregled_dogadjaja' id_dog=poziv.koji_dogadjaj.id%}" target="_blank">{{ poziv.koji_dogadjaj.naziv }}</a></h4>
                        <h4 class="w3-text-teal"><i
                                        class="fa fa-calendar fa-fw w3-margin-right "></i>{{ poziv.datum }}
                                </h4>
                        <hr>
                    {% endfor %}
                {% else %}
                    <br>
                    <h4>Nemate poziva na cekanju</h4>
                {% endif %}


            </div>

        </div>
    </div>
</div>

<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Placeholder -->
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

dogadjaji/templates/dogadjaji/zavrsen.html
<!DOCTYPE html>
<html>
<head>
    <title>MAXO</title>
</head>
<body>
<center>
    <h1 style="font-family: Arial; margin-top: 20vh;">
Datum odrzavanja ovog dogadjaja jos nije prosao.</h1> <br> <h3>Datum odrzavanja je namesten na: {{ datum }}</h3>

</center>



</body>
</html>