RAF2019/urls.py
from django.contrib import admin
from django.urls import path, include
from korisnici import views

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('reset_lozinka/', auth_views.PasswordResetView.as_view(template_name='korisnici/reset.html'), name = 'password_reset'),
    path('reset_lozinka/kraj/', auth_views.PasswordResetView.as_view(template_name='korisnici/reset_potvrda.html'), name = 'password_reset_done'),
    path('reset_lozinka/potvrda/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='korisnici/resetuj.html'), name = 'password_reset_confirm'),
    path('reset_lozinka/zavrsio/', auth_views.PasswordResetCompleteView.as_view(template_name='korisnici/kraj.html'), name = 'password_reset_complete'),
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('korisnici/', include('korisnici.urls'), name="korisnici"),
    path('dogadjaji/', include('dogadjaji.urls'), name="dogadjaji"),
    path('logout/', views.logoutPage, name="logoutPage"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

korisnici/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "korisnici"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profil/', views.clanInfo, name='clanInfo'),
    path('login/', views.loginPage, name='loginPage'),
    path('podesavanja/', views.podesavanja, name='podesavanja'),
    path('lozinka/', views.promenaLozinke, name='lozinka'),
    path('pregled/<int:usid>', views.pregled, name='pregled'),

    ]

korisnici/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Clanovi(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gradovi = (("Nije naveden grad", "Nije naveden grad"),
               ('Beograd', 'Beograd'), ('Valjevo', 'Valjevo'), ('Vranje', 'Vranje'), ('Zaječar', 'Zaječar'),
               ('Zrenjanin', 'Zrenjanin'), ('Jagodina', 'Jagodina'), ('Kragujevac', 'Kragujevac'),
               ('Kraljevo', 'Kraljevo'), ('Kruševac', 'Kruševac'), ('Leskovac', 'Leskovac'), ('Loznica', 'Loznica'),
               ('Niš', 'Niš'), ('Novi Pazar', 'Novi Pazar'), ('Novi Sad', 'Novi Sad'), ('Pančevo', 'Pančevo'),
               ('Požarevac', 'Požarevac'), ('Priština', 'Priština'), ('Smederevo', 'Smederevo'), ('Sombor', 'Sombor'),
               ('Sremska Mitrovica', 'Sremska Mitrovica'), ('Subotica', 'Subotica'), ('Užice', 'Užice'),
               ('Čačak', 'Čačak'), ('Šabac', 'Šabac'), ('Pirot', 'Pirot'))

    polovi = (("Musko", "Musko"), ("Zensko", "Zensko"), ("Bez navodjenja pola", "Bez navodjenja pola"))

    sportovi = (('Nije naveden omiljeni sport', "Nije naveden omiljeni sport"),
                ("Fudbal", "Fudbal"), ("Kosarka", "Kosarka"), ("Tenis", "Tenis"),
                ("Odbojka", "Odbojka"),("Rukomet","Rukomet"),("Stoni tenis","Stoni tenis"),("Bilijar","Bilijar"))

    profilna_slika = models.ImageField(default="profilne_slike/default.jpg", upload_to="profilne_slike")
    grad = models.CharField(max_length=254, default="Nije naveden grad", choices=gradovi)
    omiljeni_sport = models.CharField(max_length=254, choices=sportovi, default="Nije naveden omiljeni sport")
    pol = models.CharField(max_length=20, choices=polovi, default='Bez navodjenja pola')
    broj_telefona = models.CharField(max_length=35, default="Nije dodat broj telefona")
    opis = models.TextField(max_length=1000,blank=True, default="")
    prosecna_ocena = models.FloatField(default=0)
    instagram = models.CharField(max_length=150, default='', blank=True)
    twitter = models.CharField(max_length=150, default='', blank=True)
    firma = models.BooleanField(default=False, blank=True)

    def mailPregled(self):
        mail = self.user.email
        d = mail.split("@")
        if len(d[0])>3:
            return "***" + d[0][3:] + "@" + len(d[1].split(".")[0]) * "*" + '.' + d[1].split(".")[1]
        else:
            return mail

korisnici/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, Textarea
from .models import Clanovi
from django.core.validators import ValidationError


class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Lozinka', 'id': 'password'}))

    class Meta:
        model = User
        fields = ["username", 'first_name', 'last_name', 'email', 'password']
        widgets = {
            'username': TextInput(attrs={'class': "form-control", 'placeholder': "Korisnicko ime"}),
            'first_name': TextInput(attrs={'class': "form-control", 'placeholder': "Ime"}),
            'last_name': TextInput(attrs={'class': "form-control", 'placeholder': "Prezime"}),
            'email': EmailInput(attrs={'class': "form-control", 'placeholder': "Email adresa"}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email).exists():
            raise ValidationError("Nalog sa ovom email adresom vec postoji")
        return email

    def clean_first_name(self):
        ime = self.cleaned_data['first_name']
        return ime.title()

    def clean_last_name(self):
        prezime = self.cleaned_data['last_name']
        return prezime.title()


class ClanoviForma(forms.ModelForm):
    class Meta:
        model = Clanovi
        fields = ['profilna_slika', 'grad', 'omiljeni_sport', 'pol', 'broj_telefona', 'opis', 'instagram', 'twitter']
        widgets = {
            'grad': forms.Select(choices=Clanovi.gradovi, attrs={'class': 'form-control'}),
            'pol': forms.Select(choices=Clanovi.polovi, attrs={'class': 'form-control'}),
            'omiljeni_sport': forms.Select(choices=Clanovi.sportovi, attrs={'class': 'form-control'}),
            'broj_telefona': TextInput(attrs={'class': 'form-control', 'placeholder': "Broj telefona"}),
            'instagram': TextInput(attrs={'class': 'form-control', 'placeholder': "Instagram nalog"}),
            'twitter': TextInput(attrs={'class': 'form-control', 'placeholder': "Twitter nalog"}),
            'opis': Textarea(attrs={'class': 'form-control uredi_area', 'placeholder': 'Opis',}),

        }

    def clean_instagram(self):
        ime = self.cleaned_data['instagram']
        if ime:
            if ime[0] == '@':
                return ime[1:]
            else:
                return ime
        else:
            return ''

    def clean_twitter(self):
        ime = self.cleaned_data['twitter']
        if ime:
            if ime[0] == '@':
                return ime[1:]
            else:
                return ime
        else:
            return ''

korisnici/views.py
from django.shortcuts import render, redirect
from .models import Clanovi
from django.contrib import messages
from dogadjaji.models import Dogadjaji, Prijava, Glasao, Ocenjivanje, Poziv

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User

from django.urls import reverse
from django.http import HttpResponseRedirect

from .forms import UserForm, ClanoviForma

from django.core.mail import send_mail
from django.template.loader import render_to_string


# Create your views here.


def index(request):
    poslato = False
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('korisnici:clanInfo'))
    else:
        if request.method == "POST":
            ime_prezime = request.POST["ime"]
            email = request.POST["email"]

            firma = request.POST["firma"]

            kontakt = request.POST["kontakt"]

            poruka = request.POST["poruka"]

            msg_plain = render_to_string('email.txt', {'ime_prezime': ime_prezime, "email": email, "firma": firma,
                                                       "kontakt": kontakt, "poruka": poruka})
            msg_html = render_to_string('email_firma.html',
                                        {'ime_prezime': ime_prezime, "email": email, "firma": firma, "kontakt": kontakt,
                                         "poruka": poruka})

            send_mail(
                'Firma zahtev',
                msg_plain,
                'markocar000@gmail.com',
                ['maksimovicm000@gmail.com'],
                html_message=msg_html,
            )
            poslato = True

        else:
            poslato = False

        return render(request, 'index.html', {"poslato": poslato})


def register(request):
    greske = False
    ispis = ""
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            napraviClana = Clanovi(user=user)
            napraviClana.save()
            login(request, user)
            return HttpResponseRedirect(reverse('korisnici:clanInfo'))
        else:
            print("\n\n\n Greska prilikom registracije \n\n " + str(user_form.errors) + "\n\n\n")
            greske = True
            ispis = str(user_form.errors)
            if "A user with that username already exists." in ispis:
                ispis = "Nalog sa ovim korisnickim imenov vec postoji"
            elif "Nalog sa ovom email adresom" in ispis:
                ispis = "Nalog sa ovom email adresom vec postoji"
            elif "Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters" in ispis:
                ispis = "Korisnicko ime moze sadrzati samo slova, brojeve i karaktere: @/./+/-/_ "
            else:
                ispis = user_form.errors
    else:
        user_form = UserForm

    return render(request, "korisnici/registracija.html", context={"form": user_form, "greske": greske, "ispis": ispis})


def loginPage(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('korisnici:clanInfo'))
    greska = False
    if request.method == "POST":
        username = request.POST.get('korisnicko_ime')
        password = request.POST.get("lozinka")

        print(username)
        print(password)

        user = authenticate(username=username, password=password)
        print(user)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("korisnici:clanInfo"))
        else:
            greska = True
            print("\n\n\n")
            print("Greska prilikom unosa")
            print("\n\n\n")
            return render(request, 'korisnici/login.html', context={'greska': greska})

    else:
        return render(request, 'korisnici/login.html', context={'greska': greska})


@login_required
def clanInfo(request):
    user = request.user
    clan = Clanovi.objects.get(user=user)

    try:
        dal_glasao = Glasao.objects.filter(igrac=user, zavrsio=False)
    except Exception as e:
        dal_glasao = False
        print(e)
    rezultati_prijava = Prijava.objects.exclude(primljen="Ceka se odgovor").filter(
        prijavu_poslao=Clanovi.objects.get(user=user), prijava_za_dogadjaj__odrzano=False).exclude(
        organizator=user).order_by(
        'prijava_za_dogadjaj__datum_odrzavanja')
    ima = False
    if Dogadjaji.objects.filter(organizator=clan):
        ima = True
    print("\n\n\n")
    print(clan)
    print("\n\n\n")
    ocene_igraca = Ocenjivanje.objects.filter(koga_ocenio=clan, ocena__gt=0).order_by('-id')
    lista_glasanja = []
    for ocena in ocene_igraca:
        if ocena.ocena <= 0 or ocena.ocena > 5:
            continue
        komentar = ocena.komentar
        lista_glasanja.append((Clanovi.objects.get(user=ocena.ocenio), ocena.ocena, komentar))
    print('\n\n\n')
    print(lista_glasanja)
    print('\n\n\n')

    pozivi = Poziv.objects.filter(ko_je_pozvan=clan, pogledano="Nije pogledano")
    print(pozivi)
    return render(request, 'korisnici/clanInfo.html',
                  context={"user": user, "clan": clan, "ima": ima, 'prijave': rezultati_prijava,
                           'dal_glasao': dal_glasao, 'lista_glasanja': lista_glasanja, "pozivi": pozivi})


@login_required
def promenaLozinke(request):
    promenjeno = 'ne'
    user = request.user
    clan = Clanovi.objects.get(user=user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            promenjeno = 'da'
            return render(request, 'korisnici/promenaLozinke.html',
                          {'form': form, 'clan': clan, 'user': user, 'promenjeno': promenjeno})
        else:
            promenjeno = 'greska'
            print(form.errors)
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'korisnici/promenaLozinke.html',
                  {'form': form, 'clan': clan, 'user': user, 'promenjeno': promenjeno})


@login_required
def logoutPage(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def podesavanja(request):
    user = request.user
    clan = Clanovi.objects.get(user=user)
    greske = []
    if request.method == "POST":
        cl_form = ClanoviForma(data=request.POST, instance=clan)
        if cl_form.is_valid():
            cl_form.save(commit=True)
            if "profilna_slika" in request.FILES:
                print("\n\n\nIMA SLIKE\n\n\n")
                clan.profilna_slika = request.FILES['profilna_slika']
                clan.save()
        else:
            print("\n\n\nGRESKA")
            print(cl_form.errors)
            print("\n\n\n")

        return HttpResponseRedirect(reverse('korisnici:podesavanja'))


    else:
        cl_form = ClanoviForma
        return render(request, 'korisnici/podesavanja.html', context={"cl_form": cl_form, 'clan': clan})


@login_required
def pregled(request, usid):
    clan = Clanovi.objects.get(user_id=usid)
    user = User.objects.get(id=usid)
    print(clan.user.username)
    print(user.username)
    ocene_igraca = Ocenjivanje.objects.filter(koga_ocenio=clan, ocena__gt=0).order_by('-id')
    lista_glasanja = []
    for ocena in ocene_igraca:
        if ocena.ocena <= 0 or ocena.ocena > 5:
            continue
        komentar = ocena.komentar;
        lista_glasanja.append((Clanovi.objects.get(user=ocena.ocenio), ocena.ocena, komentar))

    return render(request, 'korisnici/pregled.html',
                  context={"user": user, "clan": clan, 'lista_glasanja': lista_glasanja})

korisnici/templates/korisnici/confirm.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}{{ site_name }} <br> Zahtev za resetovanje lozinke {% endblocktrans %}

{% trans "Idite na link ispod da bi ste resetovali svoju lozinku." %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Vase korisnicko ime:" %} {{ user.get_username }}

{% trans "MAXO" %}


{% endautoescape %}

korisnici/templates/korisnici/kraj.html
{% load staticfiles %}

<!DOCTYPE html>

	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>MAXO - promena lozinke</title>
	<meta name="author" content="MAXO" />


	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>

	</head>
	<body>

		<div class="container">
<h1>MAXO</h1>
			<div class="row">
				<div class="col-md-4 col-md-offset-4">

<p>Vasa lozinka je uspesno promenjena, <a href="{% url 'korisnici:loginPage' %}">prijavite se na svoj nalog</a></p>

				</div>
			</div>
		</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Placeholder -->
	<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>
<script>
    $('#id_email').addClass('form-control');
    $('#id_email').attr('placeholder','email')
</script>
	</body>
</html>

korisnici/templates/korisnici/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>MAXO - prijavljivanje</title>
	<meta name="author" content="MAXO" />


	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>

	</head>
	<body>

		<div class="container">
<h1>MAXO</h1>
			<div class="row">
				<div class="col-md-4 col-md-offset-4">



					<form action="{% url 'korisnici:loginPage' %}" method="post" class="fh5co-form animate-box" data-animate-effect="fadeIn">
						<h2>Prijavi se</h2>
                        {% csrf_token %}
						<div class="form-group">
							<label for="korisnicko_ime" class="sr-only">Korisnicko ime</label>
							<input type="text" class="form-control" id="korisnicko_ime" name="korisnicko_ime" placeholder="Korisnicko ime" autocomplete="off">
						</div>
						<div class="form-group">
							<label for="lozinka" class="sr-only">Lozinka</label>
							<input type="password" class="form-control" id="lozinka" name="lozinka" placeholder="Lozinka" autocomplete="off">
						</div>
						<div class="form-group">
							<p><a href="{% url 'password_reset' %}">Zaboravili ste lozinku</a></p>
						</div>
                        <div class="form-group">
							<p>Nemate nalog? <a href="{% url 'korisnici:register' %}">Registrujte se</a></p>
						</div>
                        {% if greska %}
                        <p style="color: red;">Pogresno korisnicko ime ili lozinka</p>
                        {% endif %}
						<div class="form-group">
							<center><input type="submit" value="Prijavi se" class="btn btn-primary"></center>
						</div>
					</form>

				</div>
			</div>
		</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Placeholder -->
	<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

korisnici/templates/korisnici/podesavanja.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Podesavanja naloga</title>
    <meta name="author" content="MAXO"/>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
      integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


    <link rel="shortcut icon" href="favicon.ico">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
    <style>
        .uredi_area{
            max-width: 100%;
            min-width: 100%;
            min-height: 40px;
        }
    </style>
</head>
<body onload="Gasi()">

<div class="container">

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">


        <div id="licni">
        <form method="post" enctype="multipart/form-data" class="fh5co-form animate-box" data-animate-effect="fadeIn">
            {% csrf_token %}
            <h2>Licni podaci <small><a href="{% url 'korisnici:clanInfo' %}">Vrati se na profil</a></small></h2>
             <div class="form-group">
                <p><a href="{% url 'korisnici:lozinka' %}" style="border: none; background-color: transparent;">Promena lozinke</a></p>
            </div>
        
            <div class="form-group">
                <p>Grad</p>
                {{ cl_form.grad }}
            </div>

            <div class="form-group">
                <p>Omiljeni sport</p>
                {{ cl_form.omiljeni_sport }}
            </div>

            <div class="form-group">
                <p>Broj telefona</p>
                {{ cl_form.broj_telefona }}
            </div>

            <div class="form-group">
                <p>Pol</p>
                {{ cl_form.pol }}
            </div>


            <div class="form-group">
                <p>Opis</p>
                {{ cl_form.opis }}
            </div>


            <div class="form-group">
                <p>Dodaj instagram</p>
                {{ cl_form.instagram }}
            </div>

            <div class="form-group">
                <p>Dodaj twitter</p>
                {{ cl_form.twitter }}
            </div>

            <div class="form-group">
            <p>Profilna slika</p>
            <input type='file' name="profilna_slika" id="profilna_slika" accept="image/x-png,image/gif,image/jpeg" />
                <br>
                 <div class="w3-display-container">
                    <center><img id="myImg" src="{{ clan.profilna_slika.url }}" style="width:100%; min-height: 100px; max-height: 500px;" alt="Avatar">
</center>
                </div>
            </div>





            <div class="form-group">
                <input type="submit" value="Sacuvaj izmene" class="btn btn-primary">
            </div>
        </form>
        </div>









    </div>
</div>
    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Placeholder -->
    <script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
    <!-- Waypoints -->
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <!-- Main JS -->
    <script src="{% static 'js/main.js' %}"></script>

<!-- NAMESTANJE PODATAKA -->
<script>

$("#id_opis").val("{{ clan.opis }}");
$("#id_broj_telefona").val("{{ clan.broj_telefona }}");
$("#id_grad").val("{{ clan.grad }}");
$("#id_pol").val("{{ clan.pol }}");
$("#id_omiljeni_sport").val("{{ clan.omiljeni_sport }}");
$("#id_instagram").val("{{ clan.instagram }}");
$("#id_twitter").val("{{ clan.twitter }}");


if ($("#grad") === ""){

}

</script>

<script type="text/javascript">
    $(function () {
        $(":file").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();

                reader.onload = imageIsLoaded;
                reader.readAsDataURL(this.files[0]);
            }
        });
    });

    function imageIsLoaded(e) {
        $('#myImg').attr('src', e.target.result);
        $('#yourImage').attr('src', e.target.result);
    };

</script>


    <script>
        function pregledPassworda() {
            var passShowing = $("#password").attr("type");
            if (passShowing === "password") {
                $("#password").attr("type", "text");
                $("#eye").attr("class", "fas fa-eye-slash fa-3x")
            }
            else {
                $("#password").attr("type", "password");
                $("#eye").attr("class", "fas fa-eye fa-3x")
            }
        }
    </script>

</body>
</html>

korisnici/templates/korisnici/reset_potvrda.html
{% load staticfiles %}

<!DOCTYPE html>

	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>MAXO - zaboravljena lozinka</title>
	<meta name="author" content="MAXO" />


	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>

	</head>
	<body>
		<div class="container">
<h1>MAXO</h1>
			<div class="row">
				<div class="col-md-4 col-md-offset-4">



					<div class="fh5co-form animate-box" data-animate-effect="fadeIn">
						<p>Instrukcije za resetovanje vase lozinke su poslati na dati mail.</p>
                        <p><a href="{% url 'korisnici:loginPage' %}">Prijavite se ovde</a></p>
						</div>
					</div>

				</div>
			</div>
		</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Placeholder -->
	<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>
<script>
    $('#id_email').addClass('form-control');
    $('#id_email').attr('placeholder','email')
</script>
	</body>
</html>